package StaticDEMO;

public class Client
{
    public static void main(String[] args){
         Dog dog = new Dog();
         dog.running();
    }
}
// This is Animal Static area Code... 
// This is Dog Static area Code...    
// This is Animal General area Code...
// This is Animal Construct Method...
// This is Dog General area Code...
// This is Dog Construct Method...
// I'm  Running